[package]
name = "raktar"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "raktar-api"
path = "application/main.rs"

[features]
local = []

[dependencies]
anyhow = "^1.0.68"
aws-config = "^0.55.0"
aws-sdk-s3 = "^0.25.0"
poem = "^1.3.50"
poem-lambda = "^1.3.50"
poem-openapi = { version = "^2.0.21", features = ["swagger-ui"] }
tokio = { version = "^1.23.0", features = ["macros", "rt-multi-thread"] }
tracing = "^0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["json"] }
